version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./src:/usr/src/app
      - ./files/data:/opt/data/
      - ./files/output:/opt/output
    command: ["./main.py"]

  ref:
    build:
      context: .
      dockerfile: Dockerfile.r
    volumes:
      - ./files/ref:/usr/src/app
      - ./files/data:/opt/data
      - ./files/output:/opt/output
    command: ["Rscript", "main.R"]
